### ISSUE TITLE
Compatibility with Sidekiq 7

### ISSUE THREAD

**Issue by dchun** [ixti/sidekiq-throttled#130] opened 2023-03-26 22:27 UTC
I tried to integrate Sidekiq Throttled with the new impementation of Sidekiq but I get the following error:
```
undefined method `error_handlers' for Sidekiq:Module

        Sidekiq.error_handlers << Sidekiq.method(:default_error_handler)
               ^^^^^^^^^^^^^^^
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator/exception_handler.rb:17:in `<class:Communicator>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator/exception_handler.rb:8:in `<module:Throttled>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator/exception_handler.rb:7:in `<module:Sidekiq>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator/exception_handler.rb:6:in `<main>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator.rb:5:in `<main>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled.rb:8:in `<main>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:73:in `rescue in block in require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:51:in `block in require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `each'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler.rb:176:in `require'
/Users/davidchun/code/rails/text-book/config/application.rb:7:in `<top (required)>'
/Users/davidchun/code/rails/text-book/config/environment.rb:2:in `require_relative'
/Users/davidchun/code/rails/text-book/config/environment.rb:2:in `<top (required)>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:302:in `require'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:302:in `boot_application'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:42:in `run'
/Users/davidchun/.rvm/gems/ruby-3.1.2/gems/sidekiq-7.0.7/bin/sidekiq:31:in `<top (required)>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/bin/sidekiq:25:in `load'
/Users/davidchun/.rvm/gems/ruby-3.1.2/bin/sidekiq:25:in `<main>'
/Users/davidchun/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
/Users/davidchun/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
```
I tried to find the block of code causing the error in the library but couldn't find the exception handler file in the communicator directory. Any help would be much appreciated

**Comment by alexander-storozhenko** [comment] 2023-03-27 09:05
while members create fix you can try 
```
Sidekiq.define_singleton_method(:error_handlers) { [] }
Sidekiq.define_singleton_method(:default_error_handler) { 1 }
```
before configure

**Comment by drewmoore** [comment] 2023-04-04 10:46
It looks like this repo has been moved, and this same issue is documented on that repo, as well: https://github.com/ixti/sidekiq-throttled-tmp/issues/16.

**Comment by ixti** [comment] 2023-04-07 04:32
Sorry, I had some problems on getting back control over the original repo. The issue was resolved, and the development will be handled in this repo from now on. Closing as a duplicate of #134. Will try to resolve this this or next week.

**Closed as completed by ixti** 2023-04-07 04:32 UTC

**Comment by remy727** [comment] 2023-06-20 08:41
Any update on this?

**Comment by ixti** [comment] 2023-06-20 22:27
If you're not using Sidekiq-Pro, you can use 1.0.0.alpha2 version. I will try to finalize outstanding bits and release 1.0.0 final this week.

**Comment by ixti** [comment] 2023-06-20 22:27
See #111

**Comment by taltcher** [comment] 2023-11-07 08:56
Hi @ixti - do you know when approximately we will have support for Sidekiq pro as well?

**Comment by ixti** [comment] 2023-11-07 13:03
I'm gonna bring initial support of sidekiq pro this week ( no superfetch support for now ), and will try to find the way to have full compatibility after that.
